### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by t00lxtz** [NicklasAhlberg/Bitlocker-Recovery-Key-Tool#1]
I would like to say this is a GREAT TOOL.  I have a situation where this tool would be amazing.ly helpful in many ways.  I need the source code though. I can't just install it as a downloaded EXE. If you could please help me out and post the actual source code, that would be so damn helpful you don't even know :)

**Comment by NicklasAhlberg** [comment]
Glad you like it. I have uploaded the .psf now. I think that you will need powershell studio to run it though.

//Nicklas
